# Generated by Django 5.2.3 on 2025-06-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10),
        ),
    ]
